---
site:
  title: "Configure Stratis with the command line interface"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::01-install-stratis.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.2/bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora