---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install-stratis"
      label: "Install Stratis"
      solveButton: false
    - name: "02-manage-storage"
      label: "Manage Storage"
      solveButton: false
    - name: "03-manage-filesystem"
      label: "Manage Filesystem"
      solveButton: false
    - name: "04-manage-snapshots"
      label: "Manage Snapshots"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty
